execute @e[type=armor_stand,name=shop_Armorer] ~ ~1 ~ kill @e[type=Villager,r=2]
execute @e[type=armor_stand,name=shop_Butcher] ~ ~1 ~ kill @e[type=Villager,r=2]
execute @e[type=armor_stand,name=shop_Cartographer] ~ ~1 ~ kill @e[type=Villager,r=2]
execute @e[type=armor_stand,name=shop_Cleric] ~ ~1 ~ kill @e[type=Villager,r=2]
execute @e[type=armor_stand,name=shop_Farmer] ~ ~1 ~ kill @e[type=Villager,r=2]
execute @e[type=armor_stand,name=shop_Fisherman] ~ ~1 ~ kill @e[type=Villager,r=2]
execute @e[type=armor_stand,name=shop_Fletcher] ~ ~1 ~ kill @e[type=Villager,r=2]
execute @e[type=armor_stand,name=shop_Leatherworker] ~ ~1 ~ kill @e[type=Villager,r=2]
execute @e[type=armor_stand,name=shop_Librarian] ~ ~1 ~ kill @e[type=Villager,r=2]
execute @e[type=armor_stand,name=shop_Shepherd] ~ ~1 ~ kill @e[type=Villager,r=2]
execute @e[type=armor_stand,name=shop_ToolSmith] ~ ~1 ~ kill @e[type=Villager,r=2]
execute @e[type=armor_stand,name=shop_WeaponSmith] ~ ~1 ~ kill @e[type=Villager,r=2]
execute @e[type=armor_stand,name=shop_Leonardo] ~ ~1 ~ kill @e[type=Villager,r=2]
execute @e[type=armor_stand,name=shop_Smelter] ~ ~1 ~ kill @e[type=Villager,r=2]
execute @e[type=armor_stand,name=shop_Alchemist] ~ ~1 ~ kill @e[type=Villager,r=2]

execute @e[type=armor_stand,name=shop_Armorer] ~ ~1 ~ function custom:shop_Armorer
execute @e[type=armor_stand,name=shop_Butcher] ~ ~1 ~ function custom:shop_Butcher
execute @e[type=armor_stand,name=shop_Cartographer] ~ ~1 ~ function custom:shop_Cartographer
execute @e[type=armor_stand,name=shop_Cleric] ~ ~1 ~ function custom:shop_Cleric
execute @e[type=armor_stand,name=shop_Farmer] ~ ~1 ~ function custom:shop_Farmer
execute @e[type=armor_stand,name=shop_Fisherman] ~ ~1 ~ function custom:shop_Fisherman
execute @e[type=armor_stand,name=shop_Fletcher] ~ ~1 ~ function custom:shop_Fletcher
execute @e[type=armor_stand,name=shop_Leatherworker] ~ ~1 ~ function custom:shop_Leatherworker
execute @e[type=armor_stand,name=shop_Librarian] ~ ~1 ~ function custom:shop_Librarian
execute @e[type=armor_stand,name=shop_Shepherd] ~ ~1 ~ function custom:shop_Shepherd
execute @e[type=armor_stand,name=shop_ToolSmith] ~ ~1 ~ function custom:shop_ToolSmith
execute @e[type=armor_stand,name=shop_WeaponSmith] ~ ~1 ~ function custom:shop_WeaponSmith
execute @e[type=armor_stand,name=shop_Leonardo] ~ ~1 ~ function custom:shop_Leonardo
execute @e[type=armor_stand,name=shop_Smelter] ~ ~1 ~ function custom:shop_Smelter
execute @e[type=armor_stand,name=shop_Alchemist] ~ ~1 ~ function custom:shop_Alchemist
